### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by codobyte** [DataTables/Dist-DataTables-Bootstrap5#1]
Error with Composer:
                                                                                                                                                                                              
  [InvalidArgumentException]                                                                                                                                                                  
  Could not find a version of package datatables.net/datatables.net matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.

**Comment by AllanJard** [comment]
Since resolved - I forgot about this issue.

**Comment by codo** [comment]
Apperently not solved?
In PackageDiscoveryTrait.php line 327:

  Could not find a version of package datatables.net/datatables.net matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.
