### ISSUE TITLE
Upgrading from 1.13.6 to (1.13.7 to 1.13.10)  breaks Buttons.defaults

### ISSUE THREAD

**Issue by yajra** [DataTables/Dist-DataTables-Bootstrap5#10]
### Error on 1.13.7 upto 1.13.10

```
Uncaught TypeError: Cannot read properties of undefined (reading 'defaults')
```

### Related Issues

Also reported in https://github.com/yajra/laravel-datatables-vite/issues/9. Tested and confirmed working on 1.13.6.

**Comment by AllanJard** [comment]
Can you give me a link to a test case showing the issue please? [It appears to work okay here](https://stackblitz.com/edit/vitejs-vite-fjg2n3?file=index.html%2Cmain.js%2Cstyle.css&terminal=dev).

**Comment by yajra** [comment]
[See this](https://stackblitz.com/edit/vitejs-vite-vukkhf?file=main.js)

```js
import './style.css';
import DataTable from 'datatables.net-bs5';
import 'datatables.net-buttons-bs5';

new DataTable('#example');
```

**Comment by AllanJard** [comment]
> "datatables.net-buttons-bs5": "^2.0.0"

Is the issue there. Use Buttons 3 for compatibility with DataTables 2. [Updated example](https://stackblitz.com/edit/vitejs-vite-x6aqwe?file=package.json).

**Comment by yajra** [comment]
Sorry can't update the example, using phone atm.

I have tested using 1.13.6 and works fine, once i bump to bs5 1.13.7 or 1.13.10, Buttons.defaults issue occurs.

**Comment by AllanJard** [comment]
I've updated the test case to use DataTables 1.13.x and Buttons 2.4.x: https://stackblitz.com/edit/vitejs-vite-x6aqwe?file=package.json . It runs okay, but I did have to remove package-lock.json because some references to the newer versions were still lingering and I suspect that was what was ultimately confusing Vite. With a fresh build using:

```js
  "dependencies": {
    "bootstrap": "^5.3.2",
    "datatables.net-bs5": "^1.13.0",
    "datatables.net-buttons-bs5": "^2.4.3"
  }
```

it runs okay.

**Comment by yajra** [comment]
I can't replicate the issue without using `laravel-datatables-vite`. There must be an issue with my script as it only works with 1.13.6 atm. Will try to resolve this on my repo. And might be the best time to upgrade to DataTables v2 too.

Do you have some upgrade guides or notes I can refer to? Will update all my packages to support DT v2 :beers:
