### ISSUE TITLE
CSS conflict with .card

### ISSUE THREAD

**Issue by nglessner** [DataTables/Dist-DataTables-Bootstrap5#2]
In [dataTables.bootstrap5.js](https://github.com/DataTables/Dist-DataTables-Bootstrap5/blob/master/js/dataTables.bootstrap5.js) the Default class modification adds the .card class to sProcessing.  The result is that the processing message div gets height: 100% from bootstrap 5's .card css which makes the processing message box unsightly.  I'd recommend either overriding the height in div.dataTables_processing or not using the .card class in the js at all.

**Comment by AllanJard** [comment]
This is just a distribution repo. You've also created a forum thread about it here: https://datatables.net/forums/discussion/72949/css-conflict-bootstrap-5-sprocessing-card#latest . Let's move the discussion there.
