### ISSUE TITLE
Missing jquery dependency

### ISSUE THREAD

**Issue by pickfire** [DataTables/Dist-DataTables-Bootstrap5#3]
It is missing this dependency https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js that is required for datatables to work.

The only js bundled in https://cdnjs.com/libraries/datatables.net-bs5 coming from this repository is https://cdnjs.cloudflare.com/ajax/libs/datatables.net-bs5/1.12.1/dataTables.bootstrap5.js which does not work without the bundled jquery.

**Comment by AllanJard** [comment]
Sorry about that. I've been working on the build scripts and messed up a bit. [The dependencies are back in place now](https://github.com/DataTables/Dist-DataTables-Bootstrap5/blob/c3e834006d254085c79206a5ad041f01f9e1a7fb/js/dataTables.bootstrap5.js). More work to be done (typing for example) but getting there. Going to close this specific issue as fixed.

**Comment by pickfire** [comment]
Is there a release for it? But so far I tested with the current cdnjs dependency it still didn't seemed to work. I still don't see `jquery.dataTables.min.js` in https://github.com/DataTables/Dist-DataTables-Bootstrap5/tree/master/js and I still get the error

```
Uncaught TypeError: DataTable is undefined
```

**Comment by AllanJard** [comment]
`jquery.dataTables.min.js` is in https://github.com/DataTables/Dist-DataTables/tree/master/js . That is expected - this package as a dependency on that one if you are using npm / yarn. If you are using CDNJS then yes, you need to include the JS files from both packages. Our [download builder](//datatables.net/download) can help with that. It doesn't use CDNJS, but it can help show what files you need (deselect the concat option). There isn't yet a release - that will be coming in the next week or so.

**Comment by pickfire** [comment]
> jquery.dataTables.min.js is in https://github.com/DataTables/Dist-DataTables/tree/master/js . That is expected - this package as a dependency on that one if you are using npm / yarn. If you are using CDNJS then yes, you need to include the JS files from both packages. Our [download builder](https://datatables.net/download) can help with that. It doesn't use CDNJS, but it can help show what files you need (deselect the concat option). There isn't yet a release - that will be coming in the next week or so.

I did include a newer jquery but it doesn't seemed to work either. Do I have to include the older jquery 1.5 for it to work manually from another source? download builder works but we do want to use dependencies from cdnjs, currently we use datatables cdn but ideally we don't want to have a separate cdn just for this use case.

**Comment by AllanJard** [comment]
jQuery 1.7.1 or newer (ideally 3.x) is required for DataTables. If you want to load DataTables core from CDNJS use https://cdnjs.com/libraries/datatables.net .

**Comment by pickfire** [comment]
https://cdnjs.com/libraries/datatables.net does work, but it does not seem to have bootstrap 5 styling

I tried using https://cdnjs.cloudflare.com/ajax/libs/datatables.net-bs5/1.12.1/dataTables.bootstrap5.css in additional to that, but it also doesn't work.

**Comment by AllanJard** [comment]
https://cdnjs.com/libraries/datatables.net-bs5 is where to get the styling integration of DataTables with Bootstrap 5.

If that isn't working for you, please link to a test case showing the issue. You need to include DataTables core and then the Bootstrap 5 integration for DataTables.

**Comment by pickfire** [comment]
Thanks, nice it works now. I didn't know I can combine both js. I thought the datatables.net already includes all the required js.

**Comment by AllanJard** [comment]
The DataTables core file can be augmented by various style files. The [download builder](//datatables.net/download) I mentioned before is the easiest way of getting a list of all the files you need, even if you don't use our CDN.
