### ISSUE TITLE
CSS files incorrectly merged/synced causing duplicate lines

### ISSUE THREAD

**Issue by RupertBarrow** [DataTables/Dist-DataTables-Bootstrap5#5]
CSS tokens defined at the top of the file are used in sections such as this one : 
https://github.com/DataTables/Dist-DataTables-Bootstrap5/blob/d282429e5ac1366bd1a7b1df3cc0391e1d2ca8db/css/dataTables.bootstrap5.css#L281-L304

Each time, the use of the token follows a definition of the same CSS property with hard-coded values, precisely those the token intends to replace.

These lines seem to have been incorrectly merged or auto-generated.
This issue certainly spans all the auto-synced Github repositories ...

**Comment by AllanJard** [comment]
That's actually intentional. It is to allow support for browser's which don't support CSS variables. They will parse and use the latest one they understand, so in this case, if the browser didn't understand the variable, it would use the hard coded value.

**Comment by RupertBarrow** [comment]
OK, I understand that. It's an intelligent trick !

**Comment by RupertBarrow** [comment]
By the way @AllanJard , when I try to encapsulate these CSS into an LWC Web Component, I get an error because it refuses `:root` directives. This is logical, since `:root` defines the CSS at a global level which would break encapsulation.

Maybe it would be better to use `:host` instead of `:root`, since this applies only to the component in which it is used : 
https://developer.mozilla.org/en-US/docs/Web/CSS/:host

**Comment by AllanJard** [comment]
The MDN guide says:

> Note: This has no effect when used outside a shadow DOM.

As such, I'm not sure it would be useful here would it? To be honest, I picked `:root` because [that is what Bootstrap does](https://github.com/twbs/bootstrap/blob/main/scss/_root.scss#L1).
